# Generated by Django 3.0.6 on 2020-05-13 15:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoastsAndBoasts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roastorboast', models.BooleanField()),
                ('content', models.CharField(max_length=280)),
                ('upVotes', models.IntegerField(default=0)),
                ('downVotes', models.IntegerField(default=0)),
                ('time', models.DateTimeField(default=datetime.datetime(2020, 5, 13, 15, 11, 21, 38459, tzinfo=utc))),
            ],
        ),
    ]
