# Generated by Django 3.0.6 on 2020-05-13 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghostpost', '0002_auto_20200513_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='roastsandboasts',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
