# Generated by Django 3.0.6 on 2020-05-14 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghostpost', '0003_roastsandboasts_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='roastsandboasts',
            name='secretKey',
            field=models.CharField(default='privateKey', max_length=6),
        ),
    ]
