# Generated by Django 3.0.6 on 2020-05-14 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghostpost', '0004_roastsandboasts_secretkey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roastsandboasts',
            name='secretKey',
            field=models.CharField(default='lmsauw', max_length=6),
        ),
    ]
